import Profile_medium from './profile_medium.png';
import Search from './search_black.png';
import LogoImg from './Logo.png';
import Profile_small from './profile_small.png';
import CaretDown from './CaretDown.png';
import Banner_desktop from './banner.png';
import Banner_desktop_short from './banner_shorter.png';
import CampLogo_default from './bootcamp_default.png';
import LogoIcon from './talkbout_final_logo.png';
import Rocket_emoji from './rocket_emoji.png';
import Megaphone_emoji from './megaphone_emoji.png';
import Fire_emoji from './fire_emoji.png';
import PointImg from './point.png';
import Home from './Home.png';
import Home_white from './Home_white.png';
import Boot from './Bootcamp.png';
import Boot_white from './Bootcamp_white.png';
import Qna from './Qna.png';
import Qna_white from './qna_white.png';
import Talk from './Board.png';
import Talk_white from './Board_white.png';
import Spinner_iris from './loadingspinner_256.gif';
import Spinner_white from './loadingspinner_white_256.gif';
import KakaoLogin_btn from './kakao_login_medium_narrow.png';
import GoogleLogin_btn from './google_login_light_pressed.png';
import Badge from '../image/badge 1.png';

export {Profile_medium, Search, LogoImg, Profile_small, CaretDown, Banner_desktop, Banner_desktop_short, CampLogo_default, LogoIcon, Rocket_emoji, Megaphone_emoji, Fire_emoji, PointImg, Home, Home_white, Boot, Boot_white, Qna, Qna_white, Talk, Talk_white, Spinner_iris, Spinner_white, KakaoLogin_btn, GoogleLogin_btn, Badge, };